### ISSUE TITLE
 stderr output from native app com.add0n.node

### ISSUE THREAD

**Issue by tasks-pl** [andy-portmen/native-client#89]
hi, 

i've firefox 77 and addon 'external application button', latest version 0.3.8
also just reinstalled this native-client, file version 10.16.3.0
this message pops up in browser console, sometimes:

stderr output from native app com.add0n.node: (node: xxxxx) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

is there anything i can do to fix that?
if it's not a critical issue, is there a way to block the browser console popups?
it also happened before, with earlier versions of this addon and node.exe, maybe messages were different though.

thanks

**Comment by andy-portmen** [comment]
Are you sure you are on the latest release of the native client? 0.8.9?
https://github.com/andy-portmen/native-client/releases

If so please take a screenshot of the error. The latest release does not use  the `Buffer()` method directly.

**Comment by tasks-pl** [comment]
![node](https://user-images.githubusercontent.com/59803266/85947014-ee9cd800-b950-11ea-9902-d2c458e07b7e.png)

yes, i had the same release installed as per your link, it's x64 version on win10 1803 x64 Pro.
and eventually i noticed that checking 'Do not alert application errors' in the app profiles in extension's options seems to keep the browser console from popping up automatically on such warnings, so thats actually already good enough solution for me.

i also have a different question, or feature request: in the app profiles, under 'Change window state to', could you maybe add option to keep/bring the browser to the foreground after opening the target application. for example, if im browsing a page and want to open it in chrome, i'd like it to open and load that page in the background, but currently it just jumps in front of firefox, and there seemingly isnt a command line switch for chromium browsers to get them to open minimized either.

**Comment by andy-portmen** [comment]
I just released 0.9.0, please give it a try. There should be no more "Buffer" warnings.

> could you maybe add option to keep/bring the browser to the foreground after opening the target application

It is possible to have a new option, but you will get the destination browser focused first, and then the current browser gains focus. So it is not a clean solution. It looks like if you run a batch file instead of the actual executable, you can start any application in the minimized state; https://stackoverflow.com/questions/23057448/open-program-minimized-via-command-prompt

**Comment by inge654321** [comment]
'use strict';

exports.ids = {
  chrome: [
    'lmeddoobegbaiopohmpmmobpnpjifpii', // Open in Firefox (Chrome)
    'hhalgjmpmjelidhhjldondajffjbcmcg', // Open in Firefox (Opera)
    'ajgodcbbfnpdbopgmfcgdbfhabbnilbp', // Open in Firefox (Edge)
    'poibpkhpegdblnblbkcppknekhkhmmlp', // Open in Edge (Chrome)
    'mjoebkkejejidnkfdekpbooceogbapnf', // Open in Edge (Chrome) by @rynu.smith
    'jjlkfjglmelpbkgfeebcdipalggpapag', // Open in Edge (Opera)
    'amojccmdnkdlcjcplmkijeenigbhfbpd', // Open in Opera (Chrome)
    'eokgbaidifojhfknoiicmnffiaakelpm', // Open in Opera (Edge)
    'eoenobhieedpimobhembbgdcdhdcdcig', // Open in Safari (Chrome)
    'bdlaolidgmapdilglbocpmbfipdpfjef', // Open in Safari (Opera)
    'ncemgeeikbbjoojolbihkpcoiomidhfi', // Open in IE (Edge)
    'noedpljikmfalclpadmnjbabbignpfge', // Open in IE (Opera)
    'agaecbnjediafcdopcfidcdiponjlmnk', // Open in IE (Chrome)
    'looohpideggedchhpphemdmppnmdkgfd', // Open in IE (Chrome) by @rynu.smith
    'ocnfecjfebnllnapjjoncgjnnkfmobjc', // Media Converter (Chrome) [By @InBasic]
    'fabccabfpmdadbhljpcmcbmepepfllnb', // Media Converter (Opera) [By @InBasic]
    'jgpghknlbaljigdhcjimjnkkjniiipmm', // Open in GIMP (Chrome)
    'cmjahocdpafkodabbojjaebogoigcipj', // Open in GIMP (Opera)
    'bifmfjgpgndemajpeeoiopbeilbaifdo', // External Application Button (Chrome)
    'enemdfoackoekaedijjmjlckkleokhih', // External Application Button (Opera)
    'ihpiinojhnfhpdmmacgmpoonphhimkaj', // Open in VLC (Chrome)
    'jfpmkcifglhenaihlnefaccjbmcmbigf', // Open in VLC (Opera)
    'hjfcjapkfahlmlefedkkpbbkeddpnnlc', // Open in VLC (Edge)
    'gmdcejkkcimnbfmicdpohgicekomipde', // Open in Chrome (Opera)
    'hkjcboammhlecfomgabecgoppnncbhjp', // Open in Chrome (Edge)
    'gkmonffckeeffppchajngpdakfppalfo', // Auto Shutdown (Chrome)
    'iajkcajifgglcaojccgiohphgjmoleia', // Auto Shutdown (Opera)
    'klglmiipkjlhpeeopnnlkhdomjhbkpjh', // Open in Vivaldi (Chrome)
    'ldoihpohemnbokndocafmiblepbjeacb', // Open in Vivaldi (Opera)
    'dijcjcnibopfdgbmpkgnjfdihfdeghcc', // Open in Tor Browser (Chrome)
    'emlgnifoahkaeocfmafkpnfbijoioefh', // Open in Tor Browser (Opera)
    'baailbcimkljcoiocaodblapjgklhgdm', // Open in Pale Moon (Chrome)
    'cglibgbhfapdcidmcpnbbekdanacjgkf', // Open in Pale Moon (Opera)
    'eekmpanhabepggphkcpnkngfmifkffip', // Open in Waterfox (Chrome)
    'hedcbilfmphgkpnokgcflaljgpecagfd', // Open in Waterfox (Opera)
    'kjoabfljeghcinlpjhdbdfbcflapkccm', // Tor Control (Chrome)
    'knfbgpkbkfebddfbklfpgmdjgolnkkfl', // Tor Control (Opera)
    'ijhhpgjhnfoalaedkmgpbehokefplfni', // Tor Control (Edge)
    'khgbdhkpcapllhgfekjegcinegfhjbmi', // YVAD by (Opera) [By @InBasic]
    'cehiomcamjpnfmemkmpjadaclohoibgo', // Open in PDF viewer (Chrome)
    'honagjpkinogkppkapphkpdffnegagge', // Open in PDF viewer (Opera)
    'ciphgjdgpkhlngiadnpebblpcjcoabcp', // Open in PDF viewer (Edge)
    'nfpgfobeckckemhmggkdfjkjaiikadnd', // Open in Yandex (Chrome)
    'dlobcokaeaiaihfebfhpdoongldphgkf', // Open in Yandex (Opera)
    'bffjckjhidlcnenenacdahhpbacpgapo', // Country Flags (Chrome)
    'ljealnphmlekclcdoeficainfegfjgkc', // Country Flags (Opera)
    'djlddpgigallklconlgapabopblddaki', // Edit with Photoshop (Chrome) [By @ray-lothian]
    'babedbfkpnfmnopiagfocoelpfmpldkc', // Edit with Photoshop (Opera) [By @ray-lothian]
    'kakiifnbkffafinaifemmingfmfjdklh', // Edit with Paint.Net (Chrome) [By @ray-lothian]
    'cbdomccfnegbmmpfakfpnonihdnfmonn', // Edit with Paint.Net (Opera) [By @ray-lothian]
    'oahnpfaakepnaabalmemoljdonbdjeei', // Easy Video Downloader (Opera) [By @ray-lothian]
    'eaicplkoeceoelookkiaeekhodehdhde', // Easy Video Downloader (Chrome) [By @ray-lothian]
    'oofmnabdpcibefadlibdpnnbglcehfpj', // Email Client for Notmuch [By @InBasic]
    'ghnflaojldkldmjdiocenfmeonemoogb', // Email Client for Notmuch [By @InBasic]
    'lhplfipknbnglagbgbfogdaihdcekfga', // Open in Foxit Reader [By @lunu-bounir]
    'dkkkgkdappindobbhmcjnjidkggbdiil', // Open in PDF-XChange Viewer [By @lunu-bounir]
    'bhfenhhfpcpkknkahnlogooiodcofkjl', // Open in Chromium (Chrome)
    'dilpigogejfnnahbbmnpjmccammdaiom', // Open in Chromium (Opera)
    'mgmnomlncpmfgelhofilonnecmbdaoia', // Open in Brave (Chrome) [By @brian-girko]
    'pfenoignchfmjmphnpfihgockdhejcjf', // Open in Sumatra (Chrome)
    'ojmcfmboidiokgkgmilnmjnjkdbgakpn', // Open in Sumatra (Opera)
  ],
  firefox: [
    '{b8fa78dd-dae1-4839-9d0e-ce5e213083ce}', // Open in GIMP
    '{5610edea-88c1-4370-b93d-86aa131971d1}', // Open in IE
    '{94782f74-1a58-4332-a803-00006221a9d0}', // Open in Edge
    '{3128fe8f-f039-42ea-8b12-126f78387074}', // Open in Safari
    '{8db82a75-48fd-452a-81cf-bd40b2e60dac}', // Open in Opera
    '{42dce5a2-467b-4d7b-ad11-50f4ab3d03cf}', // Open in Yandex
    '{15a602dd-abe0-4cff-875b-c5acd77727b6}', // Open in Pale Moon
    '{5cf4e3be-dd11-4589-befe-1b9e5037792b}', // Open in Waterfox
    '{0ff128a1-c286-4e73-bffa-9ae879b244d5}', // Media Converter
    '{65b77238-bb05-470a-a445-ec0efe1d66c4}', // External Application Button
    '{086f665e-6a55-4107-9147-f9a14e72b137}', // Open in Chrome
    '{6b954d17-d17c-4a19-8fe6-ee8052a562d6}', // Open in VLC
    '{9a71ec90-d0b6-44af-833f-efe418ff8454}', // Auto Shutdown
    '{0bcb72f8-7da8-4071-905c-2de13f5aad3a}', // Open in Vivaldi
    '{9d3b260b-886d-4263-b9d6-81d756ee4929}', // Open in Tor Browser
    '{f73df109-8fb4-453e-8373-f59e61ca4da3}', // YVAD [By @InBasic]
    '{d22a1484-dcef-44e9-ab52-80f0f4a331a3}', // Tor Control
    '{0d3afca0-aedf-491f-b0f9-9ffc22113ea8}', // Open in PDF viewer
    '{802a552e-13d1-4683-a40a-1e5325fba4bb}', // Country Flag
    '{e127aaca-d162-4e4c-8de6-a5ee4de1a2ec}', // Edit with Photoshop [By @ray-lothian]
    '{3e8ae4b2-678d-4a63-8104-4d4d8d3b4f46}', // Edit with Paint.Net [By @ray-lothian]
    '{cd04e15e-6b23-4648-860d-0057602a5c2a}', // Easy Video Downloader [By @ray-lothian]
    '{8e409c88-e088-4ce8-8506-5a91e6c502a8}', // Email Client for Notmuch [By @InBasic]
    '{655859e0-3c86-43a1-9794-88721dacc481}', // Open in Foxit Reader [By @lunu-bounir]
    '{00186e07-f704-41ce-90aa-b09d4f49a7db}', // Open in PDF-XChange Viewer [By @lunu-bounir]
    '{4d3bd246-4326-4ec1-bb49-a27cfd57ca08}', // Open in Chromium
    '{c88f6be2-3757-446b-be27-27eedddbcae0}', // Open in Brave [By @brian-girko]
    '{73e2414b-dc86-4e63-8ac6-231e8efe870c}', // Open in Sumatra
  ]
};

**Comment by DonW01** [comment]
I wanna thank everybody that contributes and helps 2 further all of this stuff is this too much for me right now but I know I couldn't get nothing down if somebody wasn't straightening these things out for me and I wanna thank you so very much for what you do
I hope there are enough donations contributors people who care the curious through to a better world I believe we still have the majority but not the initiative  I'm afraid  how many freshminds new ideas different ways of looking at things considering things that's what sets us apart from the animals they don't consider anything they see or hear touch smell or drawing but we are more human as we are more considerate of the things around us consider this the path to awareness in a higher thought it has to have consideration you can't do it thinking only of yourself you have to consider Halo if you wanna get down the path of it all work together is never before trust one another is never before protect yourselves as never before and let's venture into the why long endless Rd of possibilities as long as we don't screwed up be considerate

**Comment by DonW01** [comment]
Be Considerate of what you are  doing and question why in ALL things even if you think you have the answer because thee Implacasions of everything we do and think (almost) are Endless and what might seem to not cause harm today could extinct Humanity in the future 
Try to  consider those who will come after you as well as remembering the masses before that were led to slaughter and encamped
and torn from the only things they loved and swore to protect ~ Because of a miss placed consideration from "ONE Individual"  
                                          C O N S I D E R   T H A T       !  !  ! ! 
![logo-full-2x](https://user-images.githubusercontent.com/62311501/139534104-f99b56df-695b-4b76-a5c5-aad600b32730.png)
